### ISSUE TITLE
Support Intellij 2022.2 Final

### ISSUE THREAD

**Issue by natros** [GoldSubmarine/RestfulHelper#19]
## 🐛 Describe the bug
Not compatible with IntelliJ IDEA 2022.2

## ✅ Expected behavior
To work with 2022.2

## 📱 Tech info
- OS: MacOS 12.5
- Plugin version: 0.2.5-stable

**Comment by Nayacco** [comment]
I have submitted the new version and it will be reviewed and approved in two days.

Thank you for your attention to the plug-in.

**Comment by natros** [comment]
I've already compiled it and I'm using it. 

Thank you very much.
