### ISSUE TITLE
Support IntelliJ 2023.3

### ISSUE THREAD

**Issue by natros** [GoldSubmarine/RestfulHelper#23]
Hi, 

Intellij 2023.3 will be released soon and this plugin is not supported. I tried to change the version in the .xml file, but this time it gives an error in the IDE.

Thank you

**Comment by Nayacco** [comment]
I will support it in the next few days.

**Comment by Nayacco** [comment]
Have released it. You can download it from the release assets if can not wait Jetbrains audit.
